// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuSaveScreen","status":true,"description":"Alternative menu and save/load screen layout.","parameters":{"maxSavefiles":"80","maxRows":"4","maxCols":"8"}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"TextScriptBase","status":true,"description":"Text Script Base Plugin","parameters":{"TextList":"[]"}},
{"name":"ExtraWindow","status":true,"description":"Extra Window Display Per Scene Plugin","parameters":{"WindowList":"[\"{\\\"SceneName\\\":\\\"Scene_Map\\\",\\\"x\\\":\\\"720\\\",\\\"y\\\":\\\"0\\\",\\\"width\\\":\\\"234\\\",\\\"height\\\":\\\"714\\\",\\\"LineHeight\\\":\\\"32\\\",\\\"Text\\\":\\\"\\\\\\\\js<$gameParty.statusBar()>\\\",\\\"FontSize\\\":\\\"0\\\",\\\"WindowSkin\\\":\\\"\\\",\\\"SwitchId\\\":\\\"1\\\",\\\"ShowOpenAnimation\\\":\\\"true\\\"}\"]"}},
{"name":"XQK_CoreEngine","status":true,"description":"一些不止可以用于魔塔的丰富扩展功能","parameters":{}},
{"name":"XQK_MagicTower","status":true,"description":"魔塔样板核心，含有一些全局参数可供修改","parameters":{"maxTurn":"1000000","preemptive":"1","magicAttack":"0","sturdy":"1","hits":"2","breakArmor":"0.9","spike":"0.1","purify":"1","vampire":"0.25","poisonDamage":"5","cursedGold":"0","cursedExp":"0","hatredAdd":"1","hatredDecay":"0.5","explosive":"1"}}
];
